In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import itertools
import regex as re

In [2]:
grid=[(50,50,50,50,50),(150,50,25,25,25),(25,25,50,150,25)]

## R2 scores

In [3]:
scores=pd.read_csv("../results/DBTL_strategy/SGD_Regressor_scores_DBTL.csv",index_col=0)
column_dict={}# splitted name
index_list=list(scores.index)
for i,k in enumerate(index_list):
    temp=k.split("_")
    temp.append(list(scores['0'])[i])
    column_dict[i]=temp
    

scores=pd.DataFrame(column_dict).T

scores=scores.rename(columns={0:'Grid',1:"Cycle",2:"Run",3:"Value"})

In [4]:
scores

      Grid   Cycle    Run     Value
0    grid0  cycle1   run0  0.313435
1    grid0  cycle2   run0  0.347149
2    grid0  cycle3   run0  0.382091
3    grid0  cycle4   run0  0.379783
4    grid0  cycle5   run0  0.370765
..     ...     ...    ...       ...
445  grid2  cycle1  run29  0.318014
446  grid2  cycle2  run29  0.317075
447  grid2  cycle3  run29  0.318597
448  grid2  cycle4  run29  0.321543
449  grid2  cycle5  run29  0.323969

[450 rows x 4 columns]

In [121]:
CG_mean=scores.groupby(by=['Cycle','Grid'],axis=0,as_index = False).mean()
CG_min=scores.groupby(by=['Cycle','Grid'],axis=0,as_index = False).agg(np.std,ddof=0)
#0,1,6,9


# Grid0_mean=CG_mean[CG_mean['Grid']=="grid0"]
# Grid0_min=CG_min[CG_min['Grid']=="grid0"]
# print(Grid0_mean)
# print(Grid0_min)


# Grid0_mean=CG_mean[CG_mean['Grid']=="grid1"]
# Grid0_min=CG_min[CG_min['Grid']=="grid1"]
# print(Grid0_mean)
# print(Grid0_min)

Grid0_mean=CG_mean[CG_mean['Grid']=="grid2"]
Grid0_min=CG_min[CG_min['Grid']=="grid2"]
print(Grid0_mean)
print(Grid0_min)

     Cycle   Grid     Value
2   cycle1  grid2  0.296658
5   cycle2  grid2  0.333098
8   cycle3  grid2  0.334636
11  cycle4  grid2  0.336088
14  cycle5  grid2  0.335728
     Cycle   Grid     Value
2   cycle1  grid2  0.076549
5   cycle2  grid2  0.018326
8   cycle3  grid2  0.021480
11  cycle4  grid2  0.019886
14  cycle5  grid2  0.019542

/tmp/ipykernel_9596/19280744.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.mean is deprecated. In a future version, a TypeError will be raised. Before calling .mean, select only columns which should be valid for the function.
  CG_mean=scores.groupby(by=['Cycle','Grid'],axis=0,as_index = False).mean()
/tmp/ipykernel_9596/19280744.py:2: FutureWarning: Dropping invalid columns in DataFrameGroupBy.agg is deprecated. In a future version, a TypeError will be raised. Before calling .agg, select only columns which should be valid for the function.
  CG_min=scores.groupby(by=['Cycle','Grid'],axis=0,as_index = False).agg(np.std,ddof=0)

In [108]:
best_strain=pd.read_csv("../results/DBTL_strategy/SGD_Regressor_best_built_strain_DBTL.csv",index_col=0)
column_dict={}# splitted name
index_list=list(best_strain.index)
for i,k in enumerate(index_list):
    temp=k.split("_")
    temp.append(list(best_strain['0'])[i])
    column_dict[i]=temp
    

best_strain=pd.DataFrame(column_dict).T

best_strain=best_strain.rename(columns={0:'Grid',1:"Cycle",2:"Run",3:"Value"})

In [116]:
CG_mean=best_strain.groupby(by=['Cycle','Grid'],axis=0,as_index = False).mean()
CG_min=best_strain.groupby(by=['Cycle','Grid'],axis=0,as_index = False).agg(np.min)
CG_mean


Grid0_mean=CG_mean[CG_mean['Grid']=="grid2"]
Grid0_min=CG_min[CG_min['Grid']=="grid2"]

Grid0_mean

/tmp/ipykernel_9596/1892929290.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.mean is deprecated. In a future version, a TypeError will be raised. Before calling .mean, select only columns which should be valid for the function.
  CG_mean=best_strain.groupby(by=['Cycle','Grid'],axis=0,as_index = False).mean()

     Cycle   Grid      Value
2   cycle1  grid2  10.619912
5   cycle2  grid2  10.674621
8   cycle3  grid2  10.820554
11  cycle4  grid2  10.940876
14  cycle5  grid2  10.960508

### Top 100 prediction

In [107]:
best_strain=pd.read_csv("../results/DBTL_strategy/SGD_Regressor_top100_DBTL.csv",index_col=0)
column_dict={}# splitted name
index_list=list(best_strain.index)
for i,k in enumerate(index_list):
    temp=k.split("_")
    temp.append(list(best_strain['0'])[i])
    column_dict[i]=temp
    

best_strain=pd.DataFrame(column_dict).T

best_strain=best_strain.rename(columns={0:'Grid',1:"Cycle",2:"Run",3:"Value"})
CG_mean=best_strain.groupby(by=['Cycle','Grid'],axis=0,as_index = False).mean()
CG_min=best_strain.groupby(by=['Cycle','Grid'],axis=0,as_index = False).agg(np.min)
CG_mean


Grid0_mean=CG_mean[CG_mean['Grid']=="grid2"]
#Grid0_min=CG_min[CG_min['Grid']=="grid0"]
Grid0_mean

/tmp/ipykernel_9596/1180458685.py:13: FutureWarning: Dropping invalid columns in DataFrameGroupBy.mean is deprecated. In a future version, a TypeError will be raised. Before calling .mean, select only columns which should be valid for the function.
  CG_mean=best_strain.groupby(by=['Cycle','Grid'],axis=0,as_index = False).mean()

     Cycle   Grid      Value
2   cycle1  grid2  24.933333
5   cycle2  grid2  38.600000
8   cycle3  grid2  46.900000
11  cycle4  grid2  50.133333
14  cycle5  grid2  50.466667

### best built strain index, best built strain is in top 100 of simulated designs

In [103]:
comb_space=pd.read_csv("../data/combinatorial_space/combinatorial_space_pathway_A.csv")
index_top100=np.argsort(comb_space['Enzyme_G'])[::-1]
index_top100=index_top100[0:100]
index_top100=index_top100.values

best_strain=pd.read_csv("../results/DBTL_strategy/SGD_Regressor_best_built_strain_index_DBTL.csv",index_col=0)

column_dict={}# splitted name

index_list=list(best_strain.index)
for i,k in enumerate(index_list):
     temp=k.split("_")
     #temp.append(list(best_strain.loc[:,0:])[i])
     temp.append(list(best_strain['0'])[i])
     column_dict[i]=temp
    

best_strain=pd.DataFrame(column_dict).T

best_strain=pd.DataFrame(column_dict).T
best_strain=best_strain.rename(columns={0:'Grid',1:"Cycle",2:"Run",3:"Value"})
# CG_mean=best_strain.groupby(by=['Cycle','Grid'],axis=0,as_index = False).mean()
# CG_min=best_strain.groupby(by=['Cycle','Grid'],axis=0,as_index = False).agg(np.min)

np.intersect1d(best_strain['Value'],index_top100)
#CG_mean=best_strain.groupby(by=['Cycle','Grid'],axis=0,as_index = False)
best_strain=best_strain[best_strain['Grid']=="grid0"]
best_strain2=best_strain[best_strain['Cycle']=="cycle1"]
print(len(np.intersect1d(best_strain2['Value'],index_top100))/30)

best_strain2=best_strain[best_strain['Cycle']=="cycle2"]
print(len(np.intersect1d(best_strain2['Value'],index_top100))/30)

best_strain2=best_strain[best_strain['Cycle']=="cycle3"]
print(len(np.intersect1d(best_strain2['Value'],index_top100))/30)

best_strain2=best_strain[best_strain['Cycle']=="cycle4"]
print(len(np.intersect1d(best_strain2['Value'],index_top100))/30)

best_strain2=best_strain[best_strain['Cycle']=="cycle5"]
print(len(np.intersect1d(best_strain2['Value'],index_top100))/30)

0.4666666666666667
0.43333333333333335
0.4666666666666667
0.43333333333333335
0.43333333333333335

      Grid   Cycle    Run   Value
0    grid0  cycle1   run0  217386
5    grid0  cycle1   run1  271278
10   grid0  cycle1   run2  263514
15   grid0  cycle1   run3  263946
20   grid0  cycle1   run4  279060
25   grid0  cycle1   run5  270210
30   grid0  cycle1   run6  271290
35   grid0  cycle1   run7  264378
40   grid0  cycle1   run8  263298
45   grid0  cycle1   run9  263940
50   grid0  cycle1  run10  279060
55   grid0  cycle1  run11  271722
60   grid0  cycle1  run12  269988
65   grid0  cycle1  run13  279714
70   grid0  cycle1  run14  263298
75   grid0  cycle1  run15  272154
80   grid0  cycle1  run16  271074
85   grid0  cycle1  run17  279930
90   grid0  cycle1  run18  279492
95   grid0  cycle1  run19  263730
100  grid0  cycle1  run20  271062
105  grid0  cycle1  run21  279060
110  grid0  cycle1  run22  264162
115  grid0  cycle1  run23  272148
120  grid0  cycle1  run24  263946
125  grid0  cycle1  run25  279282
130  grid0  cycle1  run26  254658
135  grid0  cycle1  run27  263724
140  grid0  cycle1  run28  271290
145  grid0  cycle1  run29  263292

In [5]:
new_list=[]
for i in range(len(best_strain['Value'])):
    if best_strain['Value'].values[i] in index_top100:
        new_list.append(1)
    else:
        new_list.append(0)
best_strain['new_list']=new_list

In [10]:
comb_space.iloc[271290,:]

vmax_forward_Enzyme_A     4.000000
vmax_forward_Enzyme_B     2.000000
vmax_forward_Enzyme_C     4.000000
vmax_forward_Enzyme_D     0.500000
vmax_forward_Enzyme_E     4.000000
vmax_forward_Enzyme_F     4.000000
vmax_forward_Enzyme_G     0.250000
Enzyme_G                 10.689339
Name: 271290, dtype: float64

In [6]:
best_strain

     Grid   Cycle   Run   Value  new_list
0   grid0  cycle1  run0  269539         0
1   grid0  cycle2  run0  269539         0
2   grid0  cycle3  run0  217416         0
3   grid0  cycle4  run0  208824         0
4   grid0  cycle5  run0  208824         0
5   grid0  cycle1  run1  232404         0
6   grid0  cycle2  run1  279498         1
7   grid0  cycle3  run1  279498         1
8   grid0  cycle4  run1  279498         1
9   grid0  cycle5  run1  279498         1
10  grid0  cycle1  run2  263070         0
11  grid0  cycle2  run2  263070         0
12  grid0  cycle3  run2  263724         0
13  grid0  cycle4  run2  263724         0
14  grid0  cycle5  run2  263724         0
15  grid0  cycle1  run3  269736         0
16  grid0  cycle2  run3  269736         0
17  grid0  cycle3  run3  269736         0
18  grid0  cycle4  run3  279060         0
19  grid0  cycle5  run3  270636         0
20  grid0  cycle1  run4  255294         0
21  grid0  cycle2  run4  255294         0
22  grid0  cycle3  run4  262638         0
23  grid0  cycle4  run4  263292         0
24  grid0  cycle5  run4  263292         0
25  grid0  cycle1  run5  255942         0
26  grid0  cycle2  run5  255942         0
27  grid0  cycle3  run5  255942         0
28  grid0  cycle4  run5  256602         1
29  grid0  cycle5  run5  256602         1
30  grid0  cycle1  run6  279714         1
31  grid0  cycle2  run6  279714         1
32  grid0  cycle3  run6  279714         1
33  grid0  cycle4  run6  279714         1
34  grid0  cycle5  run6  279282         1
35  grid0  cycle1  run7  279498         1
36  grid0  cycle2  run7  279498         1
37  grid0  cycle3  run7  279498         1
38  grid0  cycle4  run7  279498         1
39  grid0  cycle5  run7  279498         1
40  grid0  cycle1  run8  255954         0
41  grid0  cycle2  run8  255954         0
42  grid0  cycle3  run8  271290         1
43  grid0  cycle4  run8  271290         1
44  grid0  cycle5  run8  255522         0
45  grid0  cycle1  run9  263724         0
46  grid0  cycle2  run9  263724         0
47  grid0  cycle3  run9  263724         0
48  grid0  cycle4  run9  263514         1
49  grid0  cycle5  run9  264162         1

# Code not used anymore

In [9]:
best_strain_1=pd.read_csv('../results/DBTL_strategy/0_100GBR_best_built_strain_DBTL.csv',index_col=0)
best_strain_1=renamer_dataframe(best_strain_1,0)
best_strain_2=pd.read_csv('../results/DBTL_strategy/100_200GBR_best_built_strain_DBTL.csv',index_col=0)
best_strain_2=renamer_dataframe(best_strain_2,100)
best_strain_3=pd.read_csv('../results/DBTL_strategy/200_300GBR_best_built_strain_DBTL.csv',index_col=0)
best_strain_3=renamer_dataframe(best_strain_3,200)
best_strain_4=pd.read_csv('../results/DBTL_strategy/300_400GBR_best_built_strain_DBTL.csv',index_col=0)
best_strain_4=renamer_dataframe(best_strain_4,300)
best_strain_5=pd.read_csv('../results/DBTL_strategy/400_500GBR_best_built_strain_DBTL.csv',index_col=0)
best_strain_5=renamer_dataframe(best_strain_5,400)
best_strain_6=pd.read_csv('../results/DBTL_strategy/500_600GBR_best_built_strain_DBTL.csv',index_col=0)
best_strain_6=renamer_dataframe(best_strain_6,500)
best_strain_7=pd.read_csv('../results/DBTL_strategy/600_700GBR_best_built_strain_DBTL.csv',index_col=0)
best_strain_7=renamer_dataframe(best_strain_7,600)
best_strain_8=pd.read_csv('../results/DBTL_strategy/700_800GBR_best_built_strain_DBTL.csv',index_col=0)
best_strain_8=renamer_dataframe(best_strain_8,700)
#best_strain_9=pd.read_csv('../results/DBTL_strategy/800_900GBR_best_built_strain_DBTL.csv',index_col=0)
#best_strain_9=renamer_dataframe(best_strain_6,800)
# best_strain_9=pd.read_csv('../results/DBTL_strategy/900_1000GBR_best_built_strain_DBTL.csv',index_col=0)
# best_strain_9=renamer_dataframe(best_strain_9,900)
best_strain_11=pd.read_csv('../results/DBTL_strategy/1100_1200GBR_best_built_strain_DBTL.csv',index_col=0)
best_strain_11=renamer_dataframe(best_strain_11,1100)

best_strain_18=pd.read_csv('../results/DBTL_strategy/1800_1900GBR_best_built_strain_DBTL.csv',index_col=0)
best_strain_18=renamer_dataframe(best_strain_11,1800)
best_strain_20=pd.read_csv('../results/DBTL_strategy/2000_2100GBR_best_built_strain_DBTL.csv',index_col=0)
best_strain_20=renamer_dataframe(best_strain_11,2000)
best_strain_24=pd.read_csv('../results/DBTL_strategy/2400_2500GBR_best_built_strain_DBTL.csv',index_col=0)
best_strain_24=renamer_dataframe(best_strain_11,2400)
best_strain_25=pd.read_csv('../results/DBTL_strategy/2500_2600GBR_best_built_strain_DBTL.csv',index_col=0)
best_strain_25=renamer_dataframe(best_strain_11,2500)



# I made a mistake here, that I later will resolve. The indexes (so grid_0) get renamed everytime to 0. So for the second file (from 100-200), it still gets called 0_100. 
# I will for now fix this by just renaming the grid_0 to 100 to 100_200. This is a really hacky way to do it but will do it for  now because this experiment will take very long

best_strain=[best_strain_1,best_strain_2,best_strain_3,best_strain_4,best_strain_5,best_strain_6,best_strain_7,best_strain_8,best_strain_11,best_strain_18,best_strain_20,best_strain_24,best_strain_25]
best_strain=pd.concat(best_strain)

index_list=list(best_strain.index)
column_dict={}# splitted name
for i,k in enumerate(index_list):
    temp=k.split("_")
    temp.append(list(best_strain['0'])[i])
    column_dict[i]=temp
    
best_strain=pd.DataFrame(column_dict).T
best_strain=best_strain.rename(columns={0:'Grid',1:"Cycle",2:"Run",3:"Value"})

In [10]:
Cycle_Grid=best_strain.groupby(by=['Cycle','Grid'],axis=0).mean()

/tmp/ipykernel_7161/3833874330.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.mean is deprecated. In a future version, a TypeError will be raised. Before calling .mean, select only columns which should be valid for the function.
  Cycle_Grid=best_strain.groupby(by=['Cycle','Grid'],axis=0).mean()

In [28]:
print(grid[Cycle_Grid['Value']['cycle4'].argmax()])
print(grid[Cycle_Grid['Value']['cycle4'].argmin()])
print(Cycle_Grid['Value']['cycle4'].max())
print(Cycle_Grid['Value']['cycle4'].min())

(20, 200, 100, 200, 100)
(20, 50, 50, 500, 200)
11.05304088231918
9.820931638470608

In [52]:
for i,k in enumerate(grid):
    if k==(100,50,20,20,20):
        print(i)

1375

## Different strategies 
Strategy 1 (S1): each cycle has equal samples

In [53]:
S1_20=best_strain.loc[best_strain['Grid']=='grid0',:]
S1_20.groupby(by=['Cycle'],axis=0).mean()

S1_50=best_strain.loc[best_strain['Grid']=='grid781',:]
S1_50.groupby(by=['Cycle'],axis=0).mean()

S1_100=best_strain.loc[best_strain['Grid']=='grid1375',:]
S1_100.groupby(by=['Cycle'],axis=0).mean()

/tmp/ipykernel_7161/184701113.py:2: FutureWarning: Dropping invalid columns in DataFrameGroupBy.mean is deprecated. In a future version, a TypeError will be raised. Before calling .mean, select only columns which should be valid for the function.
  S1_20.groupby(by=['Cycle'],axis=0).mean()
/tmp/ipykernel_7161/184701113.py:5: FutureWarning: Dropping invalid columns in DataFrameGroupBy.mean is deprecated. In a future version, a TypeError will be raised. Before calling .mean, select only columns which should be valid for the function.
  S1_50.groupby(by=['Cycle'],axis=0).mean()

Empty DataFrame
Columns: []
Index: []